# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracker.proto\x12\x07tracker\"\'\n\nLogRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\"\n\x0f\x45ntriesResponse\x12\x0f\n\x07\x65ntries\x18\x01 \x01(\t2|\n\x07Tracker\x12\x37\n\x08LogEntry\x12\x13.tracker.LogRequest\x1a\x14.tracker.LogResponse\"\x00\x12\x38\n\nGetEntries\x12\x0e.tracker.Empty\x1a\x18.tracker.EntriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=65
  _globals['_LOGRESPONSE']._serialized_start=67
  _globals['_LOGRESPONSE']._serialized_end=96
  _globals['_EMPTY']._serialized_start=98
  _globals['_EMPTY']._serialized_end=105
  _globals['_ENTRIESRESPONSE']._serialized_start=107
  _globals['_ENTRIESRESPONSE']._serialized_end=141
  _globals['_TRACKER']._serialized_start=143
  _globals['_TRACKER']._serialized_end=267
# @@protoc_insertion_point(module_scope)
