# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tracker_pb2 as tracker__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tracker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackerStub(object):
    """Опис сервісу
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogEntry = channel.unary_unary(
                '/tracker.Tracker/LogEntry',
                request_serializer=tracker__pb2.LogRequest.SerializeToString,
                response_deserializer=tracker__pb2.LogResponse.FromString,
                _registered_method=True)
        self.GetEntries = channel.unary_unary(
                '/tracker.Tracker/GetEntries',
                request_serializer=tracker__pb2.Empty.SerializeToString,
                response_deserializer=tracker__pb2.EntriesResponse.FromString,
                _registered_method=True)


class TrackerServicer(object):
    """Опис сервісу
    """

    def LogEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEntry,
                    request_deserializer=tracker__pb2.LogRequest.FromString,
                    response_serializer=tracker__pb2.LogResponse.SerializeToString,
            ),
            'GetEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntries,
                    request_deserializer=tracker__pb2.Empty.FromString,
                    response_serializer=tracker__pb2.EntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracker.Tracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracker.Tracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tracker(object):
    """Опис сервісу
    """

    @staticmethod
    def LogEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/LogEntry',
            tracker__pb2.LogRequest.SerializeToString,
            tracker__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/GetEntries',
            tracker__pb2.Empty.SerializeToString,
            tracker__pb2.EntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
